// <auto-generated />
using System;
using GroceryStore.Database.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroceryStore.Database.Migrations
{
    [DbContext(typeof(GroceryStoreDbContext))]
    [Migration("20260826065908_SeedLocations")]
    partial class SeedLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.Property<int>("AllergensId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AllergensId", "IngredientsId");

                    b.HasIndex("IngredientsId");

                    b.ToTable("AllergenIngredient");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CategoryRecipe");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("allergens");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Carbohydrates")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("ingredients");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Location", b =>
                {
                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ZipCode");

                    b.HasIndex("ZipCode")
                        .IsUnique();

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            ZipCode = "20095",
                            City = "Hamburg - Altstadt"
                        },
                        new
                        {
                            ZipCode = "20099",
                            City = "Hamburg - St. Georg"
                        },
                        new
                        {
                            ZipCode = "20144",
                            City = "Hamburg - Eimsbüttel"
                        },
                        new
                        {
                            ZipCode = "20251",
                            City = "Hamburg - Eppendorf"
                        },
                        new
                        {
                            ZipCode = "20253",
                            City = "Hamburg - Hoheluft-Ost"
                        },
                        new
                        {
                            ZipCode = "20354",
                            City = "Hamburg - Neustadt"
                        },
                        new
                        {
                            ZipCode = "20357",
                            City = "Hamburg - Sternschanze"
                        },
                        new
                        {
                            ZipCode = "20359",
                            City = "Hamburg - St. Pauli"
                        },
                        new
                        {
                            ZipCode = "20457",
                            City = "Hamburg - HafenCity"
                        },
                        new
                        {
                            ZipCode = "21029",
                            City = "Hamburg - Bergedorf"
                        },
                        new
                        {
                            ZipCode = "21073",
                            City = "Hamburg - Harburg"
                        },
                        new
                        {
                            ZipCode = "21107",
                            City = "Hamburg - Wilhelmsburg"
                        },
                        new
                        {
                            ZipCode = "22081",
                            City = "Hamburg - Barmbek-Süd"
                        },
                        new
                        {
                            ZipCode = "22303",
                            City = "Hamburg - Winterhude"
                        },
                        new
                        {
                            ZipCode = "22335",
                            City = "Hamburg - Fuhlsbüttel"
                        },
                        new
                        {
                            ZipCode = "22529",
                            City = "Hamburg - Lokstedt"
                        },
                        new
                        {
                            ZipCode = "22765",
                            City = "Hamburg - Ottensen"
                        },
                        new
                        {
                            ZipCode = "22767",
                            City = "Hamburg - Altona-Altstadt"
                        },
                        new
                        {
                            ZipCode = "22769",
                            City = "Hamburg - Altona-Nord"
                        },
                        new
                        {
                            ZipCode = "10115",
                            City = "Berlin - Mitte"
                        },
                        new
                        {
                            ZipCode = "10117",
                            City = "Berlin - Mitte"
                        },
                        new
                        {
                            ZipCode = "10243",
                            City = "Berlin - Friedrichshain"
                        },
                        new
                        {
                            ZipCode = "10435",
                            City = "Berlin - Prenzlauer Berg"
                        },
                        new
                        {
                            ZipCode = "10585",
                            City = "Berlin - Charlottenburg"
                        },
                        new
                        {
                            ZipCode = "10785",
                            City = "Berlin - Tiergarten"
                        },
                        new
                        {
                            ZipCode = "10829",
                            City = "Berlin - Schöneberg"
                        },
                        new
                        {
                            ZipCode = "10969",
                            City = "Berlin - Kreuzberg"
                        },
                        new
                        {
                            ZipCode = "12043",
                            City = "Berlin - Neukölln"
                        },
                        new
                        {
                            ZipCode = "13353",
                            City = "Berlin - Wedding"
                        },
                        new
                        {
                            ZipCode = "80331",
                            City = "München - Altstadt"
                        },
                        new
                        {
                            ZipCode = "80336",
                            City = "München - Ludwigsvorstadt"
                        },
                        new
                        {
                            ZipCode = "80538",
                            City = "München - Lehel"
                        },
                        new
                        {
                            ZipCode = "80799",
                            City = "München - Maxvorstadt"
                        },
                        new
                        {
                            ZipCode = "80802",
                            City = "München - Schwabing"
                        },
                        new
                        {
                            ZipCode = "81667",
                            City = "München - Haidhausen"
                        },
                        new
                        {
                            ZipCode = "50667",
                            City = "Köln - Altstadt-Nord"
                        },
                        new
                        {
                            ZipCode = "50674",
                            City = "Köln - Neustadt-Süd"
                        },
                        new
                        {
                            ZipCode = "50678",
                            City = "Köln - Altstadt-Süd"
                        },
                        new
                        {
                            ZipCode = "50823",
                            City = "Köln - Ehrenfeld"
                        },
                        new
                        {
                            ZipCode = "50931",
                            City = "Köln - Lindenthal"
                        },
                        new
                        {
                            ZipCode = "60311",
                            City = "Frankfurt am Main - Altstadt"
                        },
                        new
                        {
                            ZipCode = "60313",
                            City = "Frankfurt am Main - Innenstadt"
                        },
                        new
                        {
                            ZipCode = "60316",
                            City = "Frankfurt am Main - Ostend"
                        },
                        new
                        {
                            ZipCode = "60325",
                            City = "Frankfurt am Main - Westend"
                        },
                        new
                        {
                            ZipCode = "60594",
                            City = "Frankfurt am Main - Sachsenhausen"
                        },
                        new
                        {
                            ZipCode = "70173",
                            City = "Stuttgart - Mitte"
                        },
                        new
                        {
                            ZipCode = "70178",
                            City = "Stuttgart - Süd"
                        },
                        new
                        {
                            ZipCode = "04109",
                            City = "Leipzig - Mitte"
                        },
                        new
                        {
                            ZipCode = "04275",
                            City = "Leipzig - Südvorstadt"
                        });
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreparationTime")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredients");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ZipCode");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ZipCode");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AllergenIngredient", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Allergen", null)
                        .WithMany()
                        .HasForeignKey("AllergensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryStore.Database.Entities.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryStore.Database.Entities.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Allergen", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Category", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Ingredient", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Supplier", "Supplier")
                        .WithMany("Ingredients")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Order", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.OrderItem", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Ingredient", "Ingredient")
                        .WithMany("OrderItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryStore.Database.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Recipe", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Supplier", "Supplier")
                        .WithMany("Recipes")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceryStore.Database.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Supplier", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Location", "ZipCodeNavigation")
                        .WithMany("Suppliers")
                        .HasForeignKey("ZipCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZipCodeNavigation");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.User", b =>
                {
                    b.HasOne("GroceryStore.Database.Entities.Location", "ZipCodeNavigation")
                        .WithMany("Users")
                        .HasForeignKey("ZipCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZipCodeNavigation");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Ingredient", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Location", b =>
                {
                    b.Navigation("Suppliers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.Supplier", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("GroceryStore.Database.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
